Repository Goormkdt-WebIDE/project6sIDE-FE, pull requests merged in 2023-09, with the labels that each got.

#14 회원가입 통신 구현
  package-lock.json
  package.json
  src/components/EmailInput.tsx
  src/pages/Register.tsx
Labels: new feature

#15 Login
  package-lock.json
  package.json
  src/App.tsx
  src/pages/Login.tsx
  src/pages/Register.tsx
Labels: new feature

#16 password reset 통신 구현
  src/components/EmailInput.tsx
  src/pages/Login.tsx
  src/pages/PasswordReset.tsx
  src/pages/Register.tsx
Labels: new feature

#18 회원가입 알림창 변경
  package-lock.json
  package.json
  src/components/SubmitButton.tsx
  src/layout/Layout.tsx
  src/pages/Register.tsx
Labels: design

#20 toast 사용하는 부분 리팩토링
  src/pages/Login.tsx
  src/pages/PasswordReset.tsx
  src/pages/Register.tsx
  src/service/toast.ts
Labels: refactor

#21 Testing
  jest.config.ts
  package-lock.json
  package.json
  src/components/EmailInput.tsx
  src/components/NameInput.tsx
  src/components/PasswordInput.tsx
  src/components/test/EmailInput.test.tsx
  src/components/test/NameInput.test.tsx
  src/components/test/PasswordInput.test.tsx
  src/components/test/SubmitButton.test.tsx
  src/components/test/__snapshots__/EmailInput.test.tsx.snap
  src/components/test/__snapshots__/NameInput.test.tsx.snap
  src/components/test/__snapshots__/PasswordInput.test.tsx.snap
  src/components/test/__snapshots__/SubmitButton.test.tsx.snap
  src/test/__mocks__/fileMock.js
  tsconfig.json
Labels: testing

#22 vite를 활용하여 만든 리액트 앱을 netlify에 배포할 때, 라우팅을 인식하지 못하는 오류 수정
  public/_redirects
  public/background.jpeg
  src/pages/Login.tsx
  src/pages/PasswordReset.tsx
  src/pages/Register.tsx
Labels: fix

#23 유닛 Testing (페이지 레벨)
  src/App.tsx
  src/context/AuthContext.tsx
  src/pages/Login.tsx
  src/pages/PasswordReset.tsx
  src/pages/Register.tsx
  src/pages/test/Login.test.tsx
  src/pages/test/PasswordReset.test.tsx
  src/pages/test/Register.test.tsx
  src/pages/test/__snapshots__/Login.test.tsx.snap
  src/pages/test/__snapshots__/PasswordReset.test.tsx.snap
  src/pages/test/__snapshots__/Register.test.tsx.snap
  src/test/utils.tsx
Labels: testing

#27 로그인, 회원가입, 비밀번호 리셋 네트워크 통신 에러 해결
  src/common/constant.ts
  src/context/AuthContext.tsx
Labels: fix
