Repository Goormkdt-WebIDE/project6sIDE-FE, pull requests merged in 2023-10, with the labels that each got.

#29 feature/project
  src/components/NewProjectBtn.tsx
  src/pages/Main.tsx
Labels: new feature

#30 에디터 폴더 구조 리스트에 파일 및 디렉토리 표시
  package-lock.json
  package.json
  public/data/project.json
  src/App.tsx
  src/components/NewProjectBtn.tsx
  src/components/form/EmailInput.tsx
  src/components/form/NameInput.tsx
  src/components/form/PasswordInput.tsx
  src/components/form/SubmitButton.tsx
  src/components/ide/Editor.tsx
  src/components/ide/IDEEditButton.tsx
  src/components/ide/IDEFileButton.tsx
  src/components/ide/IDEHeader.tsx
  src/components/ide/IDEMenuBar.tsx
  src/components/ide/IDEMenuButton.tsx
  src/components/ide/IDESaveButton.tsx
  src/components/ide/TreeView.tsx
  src/components/test/EmailInput.test.tsx
  src/components/test/NameInput.test.tsx
  src/components/test/PasswordInput.test.tsx
  src/components/test/SubmitButton.test.tsx
  src/index.css
  src/layout/Layout.tsx
  src/pages/IDE.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/PasswordReset.tsx
  src/pages/Register.tsx
  src/pages/test/Login.test.tsx
Labels: new feature, refactor

#32 유저 로그인 시 유저 정보 저장하는 기능 구현
  src/App.tsx
  src/components/ide/TreeView.tsx
  src/context/AuthContext.tsx
  src/pages/IDE.tsx
  src/pages/Login.tsx
  src/test/utils.tsx
Labels: new feature

#36 채팅 UI, 기능 구현
  index.html
  package-lock.json
  package.json
  src/components/Chatting.tsx
  src/pages/Main.tsx
Labels: new feature

#37 IDE 기능 구현 완료
  README.md
  src/App.tsx
  src/components/ide/Editor.tsx
  src/components/ide/IDEEditButton.tsx
  src/components/ide/IDEFileButton.tsx
  src/components/ide/IDEHeader.tsx
  src/components/ide/IDEMenuBar.tsx
  src/components/ide/IDEMenuButton.tsx
  src/components/ide/IDESaveButton.tsx
  src/components/ide/TreeView.tsx
  src/context/AuthContext.tsx
  src/pages/IDE.tsx
  src/pages/Main.tsx
Labels: new feature

#38 로우레벨 리팩터링 + TreeView 스타일링 개선
  src/common/constant.ts
  src/components/ide/Editor.tsx
  src/components/ide/Node.tsx
  src/components/ide/NodeActions.tsx
  src/components/ide/NodeFileIcon.tsx
  src/components/ide/NodeName.tsx
  src/components/ide/NodeToggleArrow.tsx
  src/components/ide/TreeView.tsx
  src/components/types/TreeView.types.ts
  src/pages/IDE.tsx
  src/service/http-requests/ide-api.ts
  src/service/http-requests/user-api.ts
Labels: refactor

#39 채팅 검색 기능 추가, 코드 리팩토링
  src/components/Chatting.tsx
  src/components/chatting/Chatting.tsx
  src/components/chatting/MessageInput.tsx
  src/components/chatting/MessagePresenter.tsx
  src/components/chatting/SearchInput.tsx
  src/components/ide/Editor.tsx
  src/pages/IDE.tsx
Labels: new feature, refactor

#40 빌드 타임 에러 수정 + 스타일링 수정
  src/components/chatting/Chatting.tsx
  src/components/chatting/MessagePresenter.tsx
  src/components/ide/Editor.tsx
  src/components/ide/TreeView.tsx
  src/pages/IDE.tsx
Labels: new feature, fix

#41 유저가 인증이 필요한 경로에 그냥 가는 것을 막고, 유효하지 않은 경로로 가는 것을 막는 기능 구현
  src/App.tsx
  src/pages/NotFound.tsx
  src/pages/ProtectedRoute.tsx
Labels: new feature

#42 프로젝트 삭제 기능 구현
  src/common/constant.ts
  src/components/project/MyProjects.tsx
  src/hook/useAllProjects.tsx
  src/service/http-requests/ide-api.ts
Labels: new feature

#44 반응형 스타일링 구현
  package-lock.json
  package.json
  src/components/chatting/Chatting.tsx
  src/components/ide/Editor.tsx
  src/components/ide/IDEHeader.tsx
  src/components/ide/IDEMenuBar.tsx
  src/components/ide/Menu.css
  src/components/ide/TreeView.tsx
  src/components/project/NewProject.tsx
  src/pages/IDE.tsx
  src/pages/Main.tsx
Labels: new feature

#45 로그인 정보 유지 로직 수정
  src/context/AuthContext.tsx
  src/pages/ProtectedRoute.tsx
  src/test/utils.tsx
Labels: fix

#47 스마트폰 환경에서 저장하기 실행했을 때 저장안되는 버그 수정
  src/components/ide/Editor.tsx
  src/pages/IDE.tsx
Labels: fix

#48 라이트, 다크모드 기능 재추가
  public/background-dark.jpg
  src/components/TopBtnContainer.tsx
  src/components/ide/Editor.tsx
  src/components/ide/Node.tsx
  src/components/ide/NodeActions.tsx
  src/components/ide/NodeFileIcon.tsx
  src/components/ide/NodeName.tsx
  src/components/ide/NodeToggleArrow.tsx
  src/components/ide/TreeView.tsx
  src/context/isDarkModeContext.tsx
  src/index.css
  src/layout/Layout.tsx
  src/pages/IDE.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/PasswordReset.tsx
  src/pages/Register.tsx
  src/pages/test/__snapshots__/Login.test.tsx.snap
  src/pages/test/__snapshots__/PasswordReset.test.tsx.snap
  src/pages/test/__snapshots__/Register.test.tsx.snap
Labels: new feature

#49 채팅 검색 기능 오류 수정
  package-lock.json
  package.json
  src/components/chatting/Chatting.tsx
  src/components/chatting/MessagePresenter.tsx
Labels: fix

#50 로그아웃 기능 구현
  src/components/TopBtnContainer.tsx
  src/context/AuthContext.tsx
Labels: new feature

#51 메시지 검색 시 윈도우 전체 뷰포트가 움직이는 문제 수정
  src/components/TopBtnContainer.tsx
  src/components/chatting/Chatting.tsx
  src/components/chatting/MessageInput.tsx
  src/components/chatting/MessagePresenter.tsx
  src/components/chatting/SearchInput.tsx
Labels: fix

#53 로그인 한 사용자가 로그인, 회원가입 페이지에 가는 것 막기
  src/App.tsx
  src/layout/Layout.tsx
  src/pages/AuthRedirect.tsx
Labels: new feature
